# Generated by Django 5.2.10 on 2026-02-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalOrganization",
            fields=[
                (
                    "global_org_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "global_org_name",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "global_acronym",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("usage_count", models.IntegerField()),
            ],
            options={
                "db_table": "global_organization",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GoSimilarity",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "source_global_org_id",
                        "target_global_org_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "similarity_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
            options={
                "db_table": "go_similarity",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrgMapping",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("instance_org_id", models.IntegerField(blank=True, null=True)),
                (
                    "instance_org_name",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "instance_org_acronym",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "instance_org_type",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                ("parent_instance_org_id", models.IntegerField(blank=True, null=True)),
                (
                    "fund_name",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("fund_id", models.IntegerField(blank=True, null=True)),
                (
                    "match_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "org_mapping",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DataSyncLog",
            fields=[
                ("sync_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("global_org", "Global Organization"),
                            ("org_mapping", "Organization Mapping"),
                            ("full", "Full Sync"),
                        ],
                        max_length=50,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("records_fetched", models.IntegerField(default=0)),
                ("records_created", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("records_deleted", models.IntegerField(default=0)),
                (
                    "data_checksum",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("no_changes", "No Changes"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("triggered_by", models.CharField(default="auto", max_length=50)),
            ],
            options={
                "db_table": "data_sync_log",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["-started_at"], name="data_sync_l_started_8f03fe_idx"
                    ),
                    models.Index(
                        fields=["sync_type", "-started_at"],
                        name="data_sync_l_sync_ty_7fda7f_idx",
                    ),
                    models.Index(
                        fields=["status"], name="data_sync_l_status_ede2aa_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MergeDecision",
            fields=[
                ("decision_id", models.AutoField(primary_key=True, serialize=False)),
                ("instance_org_id", models.IntegerField()),
                ("instance_org_name", models.CharField(max_length=255)),
                ("original_global_org_id", models.IntegerField()),
                ("original_global_org_name", models.CharField(max_length=255)),
                ("target_global_org_id", models.IntegerField()),
                ("target_global_org_name", models.CharField(max_length=255)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("remap", "Remap"),
                            ("merge", "Merge"),
                            ("review_later", "Review Later"),
                        ],
                        default="remap",
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "similarity_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("decided_by", models.CharField(default="admin", max_length=100)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("executed", "Executed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "executed_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("execution_notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "merge_decisions",
                "ordering": ["-decided_at"],
                "indexes": [
                    models.Index(
                        fields=["instance_org_id"],
                        name="merge_decis_instanc_0bc373_idx",
                    ),
                    models.Index(
                        fields=["original_global_org_id"],
                        name="merge_decis_origina_b04da4_idx",
                    ),
                    models.Index(
                        fields=["target_global_org_id"],
                        name="merge_decis_target__2e6495_idx",
                    ),
                    models.Index(
                        fields=["execution_status"],
                        name="merge_decis_executi_13ba10_idx",
                    ),
                    models.Index(
                        fields=["-decided_at"], name="merge_decis_decided_20387c_idx"
                    ),
                ],
            },
        ),
    ]
